spring:
  profiles:
    active: dev
  application:
    name: partner-match
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuesheng?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  #redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

